🔀 :: (#238) MealDetail Scene UI 퍼블리싱
team-xquare/xquare-iOS pull request #243
Opened 2022-09-16 11:02 UTC by rlarldud1234

## 개요
> MealDetail Scene을 퍼블리싱합니다.

## UI
<img src="Screen Shot 2022-09-16 at 19 32 55" src="https://user-images.githubusercontent.com/81291116/190624865-6624f37e-25aa-46d7-a14d-d4edc46a7ca7.png" width="150px"></img>

2022-09-16 12:35 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-09-16 13:54 UTC, kimxwan0319 requested changes

2022-09-16 13:54 UTC, kimxwan0319 commented on Application/Sources/Scene/MealDetail/Cell/MealDetailCell.swift
> +        }
P2: HStack 을 사용하지 않고도 방법이 있을것같아요

2022-09-16 13:54 UTC, kimxwan0319 commented on Application/Sources/Scene/MealDetail/Cell/MealMenuPerTimeView.swift
> +struct MealMenuPerTimeView: View {
P3: 네이밍에 그냥 time보단 mealTime이 더 좋을것같아여

2022-09-16 13:54 UTC, kimxwan0319 commented on Application/Sources/Scene/MealDetail/Cell/MealMenuPerTimeView.swift
> +    private func mealTimeToString(_ mealTime: MealTime) -> String {
P3: 이 메서드는 MealTime에 직접 구현해서 가져롸 쓰는게 좋을것같아요

2022-09-16 13:54 UTC, kimxwan0319 commented on Application/Sources/Scene/MealDetail/MealDetailView.swift
> +            .listStyle(.inset)
inset으로 한 이유가 있나요??

2022-09-16 13:54 UTC, kimxwan0319 commented on Application/Sources/Scene/MealDetail/Cell/MealMenuPerTimeView.swift
> +                .disabled(true)
disabled를 준이유가 있을까요?

2022-09-17 11:14 UTC, rlarldud1234 commented on Application/Sources/Scene/MealDetail/Cell/MealDetailCell.swift
> +        }
HStack을 안하고 해보았는데 .frame(maxWidth: .infinity)를 주니깐 전체로 주면 값들이 가운데로 정렬되어 있고, 따로 요소에다가 주면 그 객체를 제외한 요소만 왼쪽으로 정렬이 되고 다른 것은 가운데로 정렬이 됩니다.ㅈ

2022-09-17 11:26 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-09-17 12:19 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-09-17 12:32 UTC, kimxwan0319 approved these changes

2022-09-17 12:46 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-09-17 12:47 UTC, merged

2022-09-17 12:48 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃