🔀 :: (#244) 월별급식메뉴 기능 구현
team-xquare/xquare-iOS pull request #319
Opened 2022-10-19 14:29 UTC by rlarldud1234

## 개요
> 월별급식메뉴 기능 구현

## UI
<img src="https://user-images.githubusercontent.com/81291116/196720069-761b1eac-c95e-4289-9440-267a60af1587.png" width="150px"></img>

2022-10-20 00:04 UTC, kimxwan0319 requested changes

2022-10-20 08:25 UTC, rlarldud1234 commented on Application/Sources/Scene/MealDetail/MealDetailView.swift
> +        .listStyle(.inset)
저거 안하면 리스트가 저렇게 배경화면이랑 어울러지게 안되고
약간 따로 노는 느낌 없애려고 썻어요

2022-10-21 06:58 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-21 07:04 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-21 09:01 UTC, kimxwan0319 requested changes

2022-10-21 09:01 UTC, kimxwan0319 commented on Services/MealDataService/Sources/Data/Local/Entity/MealMenu.swift
>      }
P3) MealMenu에 kcal 프로퍼티를 추가해주세요

2022-10-21 13:35 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-24 02:57 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-24 13:25 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-24 14:53 UTC, kimxwan0319 approved these changes

2022-10-24 14:53 UTC, merged

2022-10-24 16:16 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-10-24 16:17 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃