🔀 :: (#345) MealDataService LocalDB 연동
team-xquare/xquare-iOS pull request #356
Opened 2022-12-03 10:17 UTC by rlarldud1234

## 개요
> MealDataService LocalDB 연동

## UI
<img src="https://user-images.githubusercontent.com/81291116/205435980-c0582242-79c8-427e-adff-54253cbb3e26.png"></img>
<img src="https://user-images.githubusercontent.com/81291116/205435989-75df025f-7f9d-486d-a905-2f0c96aaaad8.png"></img>

2022-12-03 15:33 UTC, kimxwan0319 requested changes

2022-12-03 15:33 UTC, kimxwan0319 commented on Services/MealDataService/Sources/Data/Local/MealDataServiceSQLiteTask.swift
>  class MealDataServiceSQLiteTask {
해당 클래스의 내용을 LocalDataSourceImpl에 합쳐주세요.
따로 분리할 필요성이 없고, 싱글톤인것도 마음에 안드네요.

2022-12-04 12:21 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-05 02:57 UTC, kimxwan0319 approved these changes

2022-12-05 10:09 UTC, merged

2022-12-05 10:51 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃