🔀 :: (#367) AttachmentDataService
team-xquare/xquare-iOS pull request #368
Opened 2022-12-08 10:01 UTC by rlarldud1234

## 개요
> AttachmentDataService 구현

2022-12-08 11:03 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-12-08 12:48 UTC, kimxwan0319 requested changes

2022-12-08 23:33 UTC, rlarldud1234 commented on Services/AttachmentService/Sources/Domain/Repository/AttachmentRepository.swift
> +    func uploadImage(files: [Data]) -> Single<[String]>
저거 서버로 보낼 때 string 값으로 보내야되서 URL이 아니라 String으로 해두건예요... 그래도 url로 변환할까요?

2022-12-09 03:06 UTC, kimxwan0319 approved these changes

2022-12-09 04:36 UTC, merged

2022-12-09 05:22 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃