🔀 :: (#484) release note 구현하기
team-xquare/xquare-iOS pull request #485
Opened 2023-05-12 07:11 UTC by juyeong525

## 개요
> release note 구현하기
## 작업사항
- BugService -> ReportService로 서버 도메인에 맞게 이름 변경
- ReportService에 FetchReleaseNote 추가

## 변경로직
- 전체뷰에 사용자탭 -> 앱탭으로 변경

## UI
https://github.com/team-xquare/xquare-iOS/assets/103028061/83fe2987-1955-4d02-ab5a-9e5982b9a3ba

2023-05-12 14:26 UTC, kimxwan0319 requested changes

2023-05-12 14:26 UTC, kimxwan0319 commented on Application/Sources/Scene/ReleaseNote/ReleaseNoteView.swift
> +        VStack {
리스트같은경우엔 LazyVStack 사용해주세여

2023-05-12 14:26 UTC, kimxwan0319 commented on Application/Sources/Scene/ReleaseNote/ReleaseNoteView.swift
> +        .onDisappear { viewModel.releaseNoteList = [] }
disappear에서 리스트를 비뤄주는 로직은 왜 필요한가요?
필여하더리도 viewmodel에 리스트를 비워주는 메서드를 구현하고 그걸 허출해주는게 바람직함

2023-05-12 14:28 UTC, juyeong525 commented on Application/Sources/Scene/ReleaseNote/ReleaseNoteView.swift
> +        VStack {
넵

2023-05-12 14:30 UTC, juyeong525 commented on Application/Sources/Scene/ReleaseNote/ReleaseNoteView.swift
> +        .onDisappear { viewModel.releaseNoteList = [] }
뷰가 appear될때 애니메이션 효과를 주기 위해 필요합니다
메소드를 만들어 호출하겠습니다

2023-05-12 14:53 UTC, kimxwan0319 approved these changes

2023-05-13 00:10 UTC, BJCHO0501 approved these changes

2023-05-13 11:37 UTC, rlarldud1234 approved these changes

2023-05-14 13:49 UTC, merged