🔀 :: (#499) 마이페이지 수정
team-xquare/xquare-iOS pull request #502
Opened 2023-05-25 16:23 UTC by juyeong525

## 개요
> 마이페이지 디자인에 따라 수정 & 마이페이지 수정 뷰 퍼블리싱

## 작업사항
- 마이페이지 디자인에 따라 수정 
- 마이페이지 수정 뷰 퍼블리싱

## 변경로직
- 

## UI
깃허브 랭킹 부분이 5차 배포에 들어가는 사항임으로 주석 처리 한 상태의 ui
https://github.com/team-xquare/xquare-iOS/assets/103028061/aa7bff31-3252-4dc6-bffe-78ca08dc8c6c
깃허브 랭킹 추가 후 ui
https://github.com/team-xquare/xquare-iOS/assets/103028061/7988348f-e227-41ea-99b1-c4205f8a5ce1

2023-05-28 02:58 UTC, kimxwan0319 requested changes

2023-05-28 02:58 UTC, kimxwan0319 commented on Application/Sources/Scene/MyPage/ProfileImage/ProFileImageView.swift
> +import SwiftUI
이거 퍼일이름 왜 ProFile로 수정된걸까요??

2023-05-28 02:58 UTC, kimxwan0319 commented on Application/Sources/Scene/MyPage/ProfileImage/ProFileImageView.swift
> +            Image.camera
하단에 카메라 이미지 추가하신것같은데, 이렇게되면 프로필이미지뷰라는 네이밍이 애매해지는것같습니다.

카메라이미지부분은 프로필뷰쪽에서 따로 구현하던가 클레스이름을 수정하던가 해야할듯

2023-05-28 05:24 UTC, juyeong525 commented on Application/Sources/Scene/MyPage/ProfileImage/ProFileImageView.swift
> +import SwiftUI
원래 파일 이름이 저거였는데 제가 마이페이지 수정이라는 뷰를 만드는 과정에서 이 파일 자체를 editMypage 디렉토리 안으로 옮겼다가
마이페이지 수정을 만들지 않고 ouath사용하여 하기로 변경되서 다시 MyPage 디렉토리로 옮겼습니다!

2023-05-28 05:31 UTC, juyeong525 commented on Application/Sources/Scene/MyPage/ProfileImage/ProFileImageView.swift
> +import SwiftUI
네이밍을 다시하는 쪽으로 수정하겠습니다

2023-05-29 12:56 UTC, kimxwan0319 approved these changes

2023-05-29 13:08 UTC, rlarldud1234 approved these changes

2023-05-29 13:39 UTC, BJCHO0501 approved these changes

2023-05-29 13:42 UTC, merged