🔀 :: (#483) setting page
team-xquare/xquare-iOS pull request #503
Opened 2023-05-26 16:34 UTC by BJCHO0501

## 개요
> 설정 페이지 만들기

## 작업사항
- 설정 API연동 및 뷰 퍼블리싱

## UI
https://github.com/team-xquare/xquare-iOS/assets/80248855/f6c99cec-2994-4971-8e3b-7fb51c437c35

close #483

2023-05-28 03:14 UTC, kimxwan0319 requested changes

2023-05-28 03:14 UTC, kimxwan0319 commented on Services/NotificationService/Sources/Domain/UseCase/ActiveNotificationCategoryUseCase.swift
> +    public func excute(topic: String, isActivated: Bool) -> Completable {
이런데서도 토픽 string 말고 enum으로 받아야함

2023-05-28 03:14 UTC, kimxwan0319 commented on Services/NotificationService/Sources/Domain/UseCase/ActiveNotificationCategoryUseCase.swift
> +    public func excute(topic: String, isActivated: Bool) -> Completable {
모든 string으로 토픽 관리하고있는부분 enum으로 바꿔주세여

2023-05-28 03:14 UTC, kimxwan0319 commented on Application/Sources/Scene/Setting/SettingView.swift
> +            })
이부분 뷰모델 역할로 넘기고 메서드 호출만 하도록 해야함

2023-05-28 03:14 UTC, kimxwan0319 commented on Application/Sources/Scene/Setting/SettingView.swift
> +            })
글고 enum사용한 딕셔너리 형태로 바꾸는게 좋을듯

2023-05-28 03:14 UTC, kimxwan0319 commented on Application/Sources/Scene/Setting/SettingViewModel.swift
> +    }
view에서 토픽마다 각각 호출햐주는 거 확인했는데
왜 서버에서 동시에 보내주도록 안되어있는건가여?

특정이유가있는거라면 usecase쪽에서 딕셔너리 배열형태로 받아서 한번에 처리할수있도록 가는게 좋아보입니다.

2023-05-28 09:35 UTC, BJCHO0501 commented on Application/Sources/Scene/Setting/SettingViewModel.swift
> +    }
view에서 forEach를 돌리는걸 viewModel로 옳기긴 했는데 enum 딕셔너리 배열을 선언한 다음에 forEach를 돌려서 key와 value를 구하려 할때 keys와 values를 또 forEach를 돌려서 처리해야 할까요..? 방법을 모르겠습니다..

2023-05-29 14:23 UTC, kimxwan0319 approved these changes

2023-05-29 14:40 UTC, rlarldud1234 approved these changes

2023-05-29 14:41 UTC, juyeong525 approved these changes

2023-05-29 15:08 UTC, merged