🔀 :: (#511) mypage republishing
team-xquare/xquare-iOS pull request #513
Opened 2023-06-01 00:18 UTC by BJCHO0501

## 개요
> 마이페이지의 디자인 변경에 따라 디자인 수정

## 작업사항
- 마이페이지 디자인 수정
- 디자인 시스템 폰트 변경 대응

## UI
<img src="https://github.com/team-xquare/xquare-iOS/assets/80248855/690673ec-d7d3-44a6-bd58-5d23b6254f17" width="150px"></img>

close #511

2023-06-01 02:00 UTC, juyeong525 commented on Application/Sources/Scene/Entire/ServiceList/ServiceSectionButtonView.swift
> +    var services: [(text: String, action: () -> Void, textColor: Color)]
textColor 옵셔널 처리하면 매번 안받아도 되지 않나요?

2023-06-01 09:19 UTC, BJCHO0501 commented on Application/Sources/Scene/Entire/ServiceList/ServiceSectionButtonView.swift
> +    var services: [(text: String, action: () -> Void, textColor: Color)]
옵셔널 처리해도 매번 받아야 할겁니다.

2023-06-01 13:22 UTC, kimxwan0319 approved these changes

2023-06-02 16:25 UTC, juyeong525 requested changes
린트 고쳐주세요

2023-06-02 17:23 UTC, juyeong525 requested changes

2023-06-02 17:23 UTC, juyeong525 commented on Application/Sources/Scene/MyPage/Information/MyInfoIDAndBirthDay.swift
> +                .sdText(type: .caption2)
textColor가 gray800입니다

2023-06-02 17:23 UTC, juyeong525 commented on Application/Sources/Scene/MyPage/Information/MyInfoIDAndBirthDay.swift
> +                .sdText(type: .caption2)
여기도 textColor가 gray800입니다

2023-06-02 17:23 UTC, juyeong525 commented on Application/Sources/Scene/MyPage/Information/MyInformationView.swift
> +//    static var previews: some View {
지워주세요

2023-06-02 17:23 UTC, juyeong525 commented on Application/Sources/Scene/MyPage/MyPageViewModel.swift
> +                self.birthDay = $0.birthDay.toString(format: "yyyy년 MM월 dd일")
디자인 보니 yyyy년 M월 d일이 맞는거 같아요

2023-06-03 11:27 UTC, juyeong525 approved these changes

2023-06-03 11:53 UTC, merged